"""
Export dense CAM priors generated by Text-guided Semantic Localization (TSL).

Purpose
-------
This script does NOT save red/blue/JET visualization images.
It saves machine-readable CAM maps for later semi-supervised training:

    out_dir/
    ├── npy/       # float32 [H, W], range 0~1, recommended for training
    ├── gray_png/  # single-channel 0~255 png, only for checking
    └── manifest.csv

Default split is all samples in Train.csv.
You can also export the labeled, unlabeled, or validation subset.


Output content
--------------
For every row in Train.csv, this script saves one CAM with the same basename and suffix as the original image under Images/.
The .npy file is float32 [H, W] in range [0, 1]. The gray PNG is only for checking.

Name rule
---------
The output filename is kept the same as the original image filename in Images/.
For example, if CSV Image is:

    mask_covid_2889.png

then the actual image path is:

    Train Set/Images/covid_2889.png

and this script saves:

    npy/covid_2889.npy
    gray_png/covid_2889.png

This matches the original image filename, not the mask filename.

Example
-------
Run from the TSL directory:

python export_tsl_cam.py ^
  --config ./configs/tsl_qata.yaml ^
  --ckpt ./save_model/tsl_qata.ckpt ^
  --out_dir "D:\\path\\to\\Train Set\\TSL_CAM"
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
import torch
import yaml
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from transformers import AutoTokenizer

# Make imports work when this file is launched directly.
THIS_DIR = Path(__file__).resolve().parent
if str(THIS_DIR) not in sys.path:
    sys.path.insert(0, str(THIS_DIR))

from utils.tsl_model import TSLGenerator, set_text_encoder_frozen  # noqa: E402


def load_yaml(path: str) -> Dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def get_split_df(
    df: pd.DataFrame,
    split: str,
    labeled_ratio: float = 0.04,
    valid_ratio: float = 0.2,
) -> pd.DataFrame:
    """Apply the same split rule used by TSLCAMDataset."""
    n_total = len(df)
    n_labeled = int(n_total * labeled_ratio)
    n_valid = int(n_total * valid_ratio)
    split = str(split).lower()

    if split in ["labeled", "cam_train", "train_labeled"]:
        out = df.iloc[:n_labeled]
    elif split == "unlabeled":
        out = df.iloc[n_labeled:n_total - n_valid]
    elif split in ["validation", "valid", "cam_valid"]:
        out = df.iloc[n_total - n_valid:]
    elif split == "rest":
        out = df.iloc[n_labeled:]
    elif split in ["all", "full"]:
        out = df
    else:
        raise ValueError(
            f"Unknown split={split}. Use labeled / unlabeled / validation / rest / all."
        )

    return out.reset_index(drop=True)


class QaTaCAMExportDataset(Dataset):
    """Dataset for exporting predicted CAM. It does not require CAM labels."""

    def __init__(
        self,
        csv_path: str,
        root_path: str,
        bert_type: str,
        image_size: Tuple[int, int] = (224, 224),
        text_max_length: int = 64,
        prompt_template: str = "Find the infected region in the chest X-ray according to the report: {report}",
        image_normalize: bool = True,
        split: str = "all",
        labeled_ratio: float = 0.04,
        valid_ratio: float = 0.2,
        trust_remote_code: bool = True,
    ):
        self.csv_path = str(csv_path)
        self.root_path = str(root_path)
        self.image_size = tuple(image_size)
        self.text_max_length = int(text_max_length)
        self.prompt_template = str(prompt_template)
        self.split = str(split)
        self.labeled_ratio = float(labeled_ratio)
        self.valid_ratio = float(valid_ratio)

        df = pd.read_csv(self.csv_path)
        if "Image" not in df.columns:
            raise ValueError(f"CSV must contain column 'Image'. Found: {list(df.columns)}")
        if "Description" in df.columns:
            self.report_column = "Description"
        elif "text" in df.columns:
            self.report_column = "text"
        else:
            raise ValueError(f"CSV must contain column 'Description' or 'text'. Found: {list(df.columns)}")

        self.df = get_split_df(
            df,
            split=self.split,
            labeled_ratio=self.labeled_ratio,
            valid_ratio=self.valid_ratio,
        )
        print(
            f"[QaTaCAMExportDataset] split={self.split}, samples={len(self.df)} / total={len(df)}, "
            f"labeled_ratio={self.labeled_ratio}, valid_ratio={self.valid_ratio}"
        )

        self.tokenizer = AutoTokenizer.from_pretrained(
            bert_type,
            trust_remote_code=trust_remote_code,
        )

        image_tfms = [
            transforms.Resize(self.image_size, interpolation=transforms.InterpolationMode.BILINEAR),
            transforms.ToTensor(),
        ]
        if image_normalize:
            image_tfms.append(
                transforms.Normalize(
                    mean=[0.485, 0.456, 0.406],
                    std=[0.229, 0.224, 0.225],
                )
            )
        self.image_transform = transforms.Compose(image_tfms)

    def __len__(self) -> int:
        return len(self.df)

    @staticmethod
    def original_image_filename_from_csv(image_name: str) -> str:
        """
        Convert CSV mask filename to the actual image filename under Images/.

        Example:
            mask_covid_2889.png -> covid_2889.png
        """
        return Path(str(image_name).replace("mask_", "")).name

    def resolve_image_path(self, csv_image_name: str) -> str:
        original_image_name = self.original_image_filename_from_csv(csv_image_name)
        return os.path.join(self.root_path, "Images", original_image_name)

    @staticmethod
    def load_rgb(path: str) -> Image.Image:
        return Image.open(path).convert("RGB")

    def __getitem__(self, idx: int) -> Dict:
        row = self.df.iloc[idx]
        csv_image_name = str(row["Image"])
        original_image_name = self.original_image_filename_from_csv(csv_image_name)
        report = str(row[self.report_column])
        text = self.prompt_template.format(report=report)

        image_path = self.resolve_image_path(csv_image_name)
        if not os.path.exists(image_path):
            raise FileNotFoundError(f"Image not found: {image_path}")

        image = self.image_transform(self.load_rgb(image_path))
        tokens = self.tokenizer(
            text,
            padding="max_length",
            truncation=True,
            max_length=self.text_max_length,
            return_tensors="pt",
        )

        return {
            "image": image,
            "input_ids": tokens["input_ids"].squeeze(0),
            "attention_mask": tokens["attention_mask"].squeeze(0),
            "csv_image_name": csv_image_name,
            "original_image_name": original_image_name,
            "image_path": image_path,
            "report": report,
            "text": text,
        }


def move_batch_to_device(batch: Dict, device: torch.device) -> Dict:
    out = {}
    for k, v in batch.items():
        if isinstance(v, torch.Tensor):
            out[k] = v.to(device, non_blocking=True)
        else:
            out[k] = v
    return out


def build_model(cfg: Dict, device: torch.device) -> TSLGenerator:
    train_cfg = cfg.get("TRAIN", {})
    model_cfg = cfg.get("MODEL", {})

    model = TSLGenerator(
        vision_type=model_cfg["vision_type"],
        bert_type=model_cfg["bert_type"],
        cam_dim=int(model_cfg.get("cam_dim", 256)),
        text_pooling=train_cfg.get("text_pooling", "mean"),
        target_size=tuple(train_cfg.get("image_size", [224, 224])),
        freeze_vision=bool(train_cfg.get("freeze_vision", False)),
        freeze_text=bool(train_cfg.get("freeze_text", True)),
        trust_remote_code=bool(model_cfg.get("trust_remote_code", True)),
        convnext_channels=model_cfg.get("convnext_channels", [96, 192, 384, 768]),
    )
    if bool(train_cfg.get("freeze_text", True)):
        set_text_encoder_frozen(model)

    model = model.to(device)
    model.eval()
    for p in model.parameters():
        p.requires_grad = False
    return model


def strip_module_prefix_if_needed(state: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
    if not state:
        return state
    keys = list(state.keys())
    if all(k.startswith("module.") for k in keys):
        return {k[len("module."):]: v for k, v in state.items()}
    return state


def load_checkpoint(model: TSLGenerator, ckpt_path: str, device: torch.device) -> None:
    if not ckpt_path:
        raise ValueError("Checkpoint path is empty. Please pass --ckpt or set TRAIN.save_dir/save_name in yaml.")
    if not os.path.exists(ckpt_path):
        raise FileNotFoundError(f"Checkpoint not found: {ckpt_path}")

    ckpt = torch.load(ckpt_path, map_location=device)
    if isinstance(ckpt, dict):
        if "model_state_dict" in ckpt:
            state = ckpt["model_state_dict"]
        elif "state_dict" in ckpt:
            state = ckpt["state_dict"]
        elif "model" in ckpt:
            state = ckpt["model"]
        else:
            state = ckpt
    else:
        raise TypeError(f"Unsupported checkpoint type: {type(ckpt)}")

    state = strip_module_prefix_if_needed(state)
    missing, unexpected = model.load_state_dict(state, strict=False)
    print(f"Loaded checkpoint: {ckpt_path}")
    if isinstance(ckpt, dict) and "epoch" in ckpt:
        print(f"  epoch={ckpt.get('epoch')}, best_val_loss={ckpt.get('best_val_loss')}")
    if missing:
        print(f"  Missing keys: {len(missing)}")
    if unexpected:
        print(f"  Unexpected keys: {len(unexpected)}")


def save_one_cam(
    cam: np.ndarray,
    original_image_name: str,
    npy_dir: Path,
    png_dir: Path,
    save_gray_png: bool = True,
    resume: bool = False,
) -> Tuple[str, str]:
    """Save one CAM using the original image filename."""
    cam = np.asarray(cam, dtype=np.float32)
    cam = np.clip(cam, 0.0, 1.0)

    original_path = Path(str(original_image_name)).name
    stem = Path(original_path).stem
    suffix = Path(original_path).suffix.lower()
    if suffix not in [".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"]:
        suffix = ".png"

    png_path = png_dir / f"{stem}{suffix}"
    npy_path = npy_dir / f"{stem}.npy"
    npy_ok = npy_path.exists() and npy_path.stat().st_size > 1024
    png_ok = (not save_gray_png) or (png_path.exists() and png_path.stat().st_size > 0)
    if resume and npy_ok and png_ok:
        return str(npy_path), str(png_path if save_gray_png else Path(""))

    npy_tmp = npy_path.with_suffix(npy_path.suffix + ".tmp")
    if npy_tmp.exists():
        npy_tmp.unlink()
    with open(npy_tmp, "wb") as f:
        np.save(f, cam.astype(np.float32))
    os.replace(npy_tmp, npy_path)

    if save_gray_png:
        gray = (cam * 255.0).round().astype(np.uint8)
        png_tmp = png_path.with_suffix(png_path.suffix + ".tmp")
        if png_tmp.exists():
            png_tmp.unlink()
        image_format = {
            ".png": "PNG",
            ".jpg": "JPEG",
            ".jpeg": "JPEG",
            ".bmp": "BMP",
            ".tif": "TIFF",
            ".tiff": "TIFF",
        }.get(suffix, "PNG")
        Image.fromarray(gray, mode="L").save(png_tmp, format=image_format)
        os.replace(png_tmp, png_path)
    else:
        png_path = Path("")

    return str(npy_path), str(png_path)


@torch.no_grad()
def export_cams(
    model: TSLGenerator,
    loader: DataLoader,
    device: torch.device,
    out_dir: Path,
    save_gray_png: bool = True,
    resume: bool = False,
    print_every: int = 20,
) -> None:
    npy_dir = out_dir / "npy"
    png_dir = out_dir / "gray_png"
    npy_dir.mkdir(parents=True, exist_ok=True)
    if save_gray_png:
        png_dir.mkdir(parents=True, exist_ok=True)

    manifest_path = out_dir / "manifest.csv"
    rows: List[Dict[str, object]] = []
    n = 0

    model.eval()
    for step, batch in enumerate(loader, start=1):
        batch = move_batch_to_device(batch, device)
        out = model(
            image=batch["image"],
            input_ids=batch["input_ids"],
            attention_mask=batch["attention_mask"],
        )

        if hasattr(out, "cam_prob"):
            prob = out.cam_prob
        elif hasattr(out, "cam_logits"):
            prob = torch.sigmoid(out.cam_logits)
        elif isinstance(out, dict) and "cam_prob" in out:
            prob = out["cam_prob"]
        elif isinstance(out, dict) and "cam_logits" in out:
            prob = torch.sigmoid(out["cam_logits"])
        else:
            prob = torch.sigmoid(out)

        prob = prob.detach().float().clamp(0.0, 1.0).cpu().numpy()
        bs = prob.shape[0]

        for i in range(bs):
            original_image_name = str(batch["original_image_name"][i])
            csv_image_name = str(batch["csv_image_name"][i])
            image_path = str(batch["image_path"][i])
            report = str(batch["report"][i])
            cam = prob[i, 0]

            npy_path, png_path = save_one_cam(
                cam=cam,
                original_image_name=original_image_name,
                npy_dir=npy_dir,
                png_dir=png_dir,
                save_gray_png=save_gray_png,
                resume=resume,
            )

            rows.append(
                {
                    "csv_image_name": csv_image_name,
                    "original_image_name": original_image_name,
                    "image_path": image_path,
                    "npy_path": npy_path,
                    "gray_png_path": png_path,
                    "cam_min": float(cam.min()),
                    "cam_max": float(cam.max()),
                    "cam_mean": float(cam.mean()),
                    "report": report,
                }
            )
            n += 1

        if print_every > 0 and step % print_every == 0:
            print(f"Exported {n} CAMs...")

    fieldnames = [
        "csv_image_name",
        "original_image_name",
        "image_path",
        "npy_path",
        "gray_png_path",
        "cam_min",
        "cam_max",
        "cam_mean",
        "report",
    ]
    with open(manifest_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Done. Exported {n} CAMs.")
    print(f"Saved npy CAMs     : {npy_dir}")
    if save_gray_png:
        print(f"Saved gray png CAMs: {png_dir}")
    print(f"Saved manifest     : {manifest_path}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=str, default="./configs/tsl_qata.yaml")
    parser.add_argument("--ckpt", type=str, default="")
    parser.add_argument("--out_dir", type=str, default="./outputs/tsl_cam")
    parser.add_argument("--csv_path", type=str, default="", help="CSV to export. Overrides DATA.test_csv_path.")
    parser.add_argument("--root_path", type=str, default="", help="Dataset root containing Images/. Overrides DATA.test_root_path.")
    parser.add_argument(
        "--split",
        type=str,
        default="all",
        choices=["labeled", "unlabeled", "validation", "rest", "all"],
        help="Default all exports every sample in the selected CSV.",
    )
    parser.add_argument("--batch_size", type=int, default=0)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument("--no_gray_png", action="store_true", help="Only save .npy, not grayscale png.")
    parser.add_argument("--resume", action="store_true", help="Skip existing complete CAM files and rewrite partial files.")
    args = parser.parse_args()

    cfg = load_yaml(args.config)
    train_cfg = cfg.get("TRAIN", {})
    model_cfg = cfg.get("MODEL", {})
    data_cfg = cfg.get("DATA", {})

    device_ids = train_cfg.get("device", [0])
    if torch.cuda.is_available():
        if isinstance(device_ids, list):
            device_id = int(device_ids[0])
        else:
            device_id = int(device_ids)
        device = torch.device(f"cuda:{device_id}")
    else:
        device = torch.device("cpu")
    print(f"Using device: {device}")

    if args.ckpt:
        ckpt_path = args.ckpt
    else:
        save_dir = Path(train_cfg.get("save_dir", "./save_model"))
        save_name = train_cfg.get("save_name", "tsl_generator.ckpt")
        ckpt_path = str(save_dir / save_name)

    csv_path = args.csv_path or data_cfg.get("test_csv_path", data_cfg["train_csv_path"])
    root_path = args.root_path or data_cfg.get("test_root_path", data_cfg["train_root_path"])

    dataset = QaTaCAMExportDataset(
        csv_path=csv_path,
        root_path=root_path,
        bert_type=model_cfg["bert_type"],
        image_size=tuple(train_cfg.get("image_size", [224, 224])),
        text_max_length=int(train_cfg.get("text_max_length", 64)),
        prompt_template=train_cfg.get(
            "prompt_template",
            "Find the infected region in the chest X-ray according to the report: {report}",
        ),
        image_normalize=bool(train_cfg.get("image_normalize", True)),
        split=args.split,
        labeled_ratio=float(train_cfg.get("labeled_ratio", data_cfg.get("labeled_ratio", 0.04))),
        valid_ratio=float(train_cfg.get("valid_ratio", data_cfg.get("valid_ratio", 0.2))),
        trust_remote_code=bool(model_cfg.get("trust_remote_code", True)),
    )

    loader = DataLoader(
        dataset,
        batch_size=args.batch_size if args.batch_size > 0 else int(train_cfg.get("valid_batch_size", train_cfg.get("batch_size", 8))),
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=torch.cuda.is_available(),
        drop_last=False,
    )

    model = build_model(cfg, device)
    load_checkpoint(model, ckpt_path, device)

    export_cams(
        model=model,
        loader=loader,
        device=device,
        out_dir=Path(args.out_dir),
        save_gray_png=not args.no_gray_png,
        resume=args.resume,
    )


if __name__ == "__main__":
    main()
